### ISSUE TITLE
List of all map on DLC [last build : 11744860 - 1.0.20230719_1750_15_112496]

### ISSUE THREAD

**Issue by Maxime66410** [jestxfot/fnafdlcruin#1]
![image](https://github.com/jestxfot/fnafdlcruin/assets/37190601/7349d270-01e6-4712-93f2-68bec415e2e8)

**Comment by lynrayy** [comment]
How to load levels?

**Comment by Maxime66410** [comment]
> How to load levels?

Open [MAP]
