### ISSUE TITLE
This is how the V.A.N.N.I mask actually works.

### ISSUE THREAD

**Issue by Maxime66410** [jestxfot/fnafdlcruin#2]
![image](https://github.com/jestxfot/fnafdlcruin/assets/37190601/a47ec3ec-31d2-43e6-9e9b-a57662197e69)

The map is duplicated in 2 parts, each time you use the mask you teleport up and down.

**Comment by jestxfot** [comment]
It is important to take into account that the maps change slightly as new generators are opened, so all the secrets in the flight mode can not be found

**Comment by Maxime66410** [comment]
> 
Yes it's normal, because the objects are considered as "Visibility = false" or "Hidden in Game = true", via the console we can reactivate/display them.

But as we can see, the maps are duplicated for each part, there must be a synchronization system between the two.
